import pkg from 'pg';
import pgvector from 'pgvector/pg';
import {getFilePaths} from './utils.js';
import {visionEmbeddingGenerator, textEmbeddingGenerator} from './model.js'


const { Client } = pkg;

export async function createTableIfNotExists(client) {
  await client.connect();
  let tableCreated = false;
  try {
    // Ensure the pgvector extension is installed
    await client.query('CREATE EXTENSION IF NOT EXISTS vector;');

    // Check if the table exists
    const checkTableExistsQuery = `
      SELECT EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = 'public'
        AND table_name = 'search_table'
      );
    `;

    const result = await client.query(checkTableExistsQuery);
    const tableExists = result.rows[0].exists;

    if (!tableExists) {
      const documentTable = `
        CREATE TABLE search_table (
          id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
          path TEXT,
          embedding vector(512)
        );
      `;
      await client.query(documentTable);
      console.log('Table created successfully');
      tableCreated = true;
    } else {
      console.log('Table already exists');
    }
  } catch (err) {
    console.error('Error creating table:', err);
  }
return tableCreated;
}


export async function insertInTable(client, filePaths) {
    // Load processor and vision model
    //await client.connect();
    await pgvector.registerTypes(client);
    try {
      for (const filePath of filePaths) {
          try {
              // Compute embeddings
              const vision_embedding = await visionEmbeddingGenerator(filePath);

              console.log(`Embeddings for ${filePath}:`, [pgvector.toSql(Array.from(vision_embedding))]);

              await client.query('INSERT INTO Search_table (path, embedding) VALUES ($1, $2)', [
                  filePath,
                  pgvector.toSql(Array.from(vision_embedding)),
              ]);
          }
          catch (err) {
              console.error(`Error processing ${filePath}:`, err);
          }
      }
  }
  finally {
      await client.end();
  }
}

function main() {
  const client = new Client({
    user: 'saradeutscher',
    host: 'localhost',
    database: 'image_db',
    port: 5432,
});
  let tableCreated = createTableIfNotExists(client);
  if (tableCreated) {
    insertInTable(client, getFilePaths('dataset'))
  }
}

main()